[package]
name = "xdp-ebpf"
version = "0.1.0"


[lib]
path = "src/main.rs"
crate-type = ["cdylib"]

[dependencies]
aya-ebpf = { version = "0.3", default-features = false, features = ["maps", "xdp"]}
aya-log-ebpf = "0.1"
network-types = "0.4"
xdp-data-structures = { path = "../xdp-data-structures" }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
